import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout from '@/app/violet_spotify_music_components_submodule/layout'
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProviderClient from "@/lib/provider/next-auth-provider";
const inter = localFont({
  src: "./fonts/inter.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const inter_italic = localFont({
  src: "./fonts/inter-italic.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter_italic.variable} antialiased`}
      >
        <NextAuthProviderClient session={session}>
          <Layout>
            {children}
          </Layout>
        </NextAuthProviderClient>
      </body>
    </html>
  );
}
